spring:
  application:
    name: eureka  #通过名称进行实例服务的调用

---
spring:
  profiles:
    awei1
server:
  port: 9000
eureka:
  client:
    register-with-eureka: true   #是否将自己注册到eureka中，默认是true，改为false，自己就是eureka
    fetch-registry: true   #是否从eureka中获取注册信息，默认true 单节点
    service-url:
#      defaultZone: http://localhost:9001/eureka/,http://localhost:9002/eureka/
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true   #是否以ip注册到eureka中

---
spring:
  profiles:
    awei2
server:
  port: 9001
eureka:
  client:
    register-with-eureka: true   #是否将自己注册到eureka中，默认是true，改为false，自己就是eureka
    fetch-registry: true   #是否从eureka中获取注册信息，默认true 单节点
    service-url:
      defaultZone: http://localhost:9000/eureka/,http://localhost:9002/eureka/
  instance:
    prefer-ip-address: true   #是否以ip注册到eureka中

---
spring:
  profiles:
    awei3
server:
  port: 9002
eureka:
  client:
    register-with-eureka: true   #是否将自己注册到eureka中，默认是true，改为false，自己就是eureka
    fetch-registry: true   #是否从eureka中获取注册信息，默认true 单节点
    service-url:
      defaultZone: http://localhost:9001/eureka/,http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true   #是否以ip注册到eureka中